# Generated by Django 3.1.5 on 2021-11-23 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0037_credit_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_hidden',
        ),
    ]
