# Generated by Django 3.1.5 on 2021-12-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0039_message_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='identification',
            field=models.IntegerField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
