# Generated by Django 3.1.5 on 2021-12-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0041_auto_20211203_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='number',
            field=models.IntegerField(),
        ),
    ]
