# Generated by Django 3.1.5 on 2022-01-14 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0045_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graffiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
