# Generated by Django 3.1.5 on 2022-03-05 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0050_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('joint_angles', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Time_a',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('task', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
