# Generated by Django 3.1.5 on 2022-03-18 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0052_tasklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incompletelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tasklist',
            new_name='Completedlist',
        ),
    ]
