# Generated by Django 3.1.5 on 2022-04-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0057_testings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testings',
            old_name='name',
            new_name='Name',
        ),
    ]
