# Generated by Django 3.1.5 on 2022-04-23 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0058_auto_20220423_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testings',
            new_name='Testing',
        ),
    ]
