# Generated by Django 3.1.5 on 2022-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0059_auto_20220423_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
