# Generated by Django 3.1.5 on 2022-04-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0062_auto_20220430_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbateam',
            name='city',
            field=models.CharField(default='las vegas', max_length=100),
        ),
        migrations.AlterField(
            model_name='nbateam',
            name='worth',
            field=models.IntegerField(),
        ),
    ]
