# Generated by Django 3.1.5 on 2022-05-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0065_remove_nbateam_ticket_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='ticket_sales',
            field=models.IntegerField(default=3000),
            preserve_default=False,
        ),
    ]
