# Generated by Django 3.1.5 on 2022-05-03 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0066_nbateam_ticket_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
        migrations.RemoveField(
            model_name='nbateam',
            name='ticket_sales',
        ),
    ]
