# Generated by Django 3.1.5 on 2022-05-03 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0068_nbateam_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
    ]
