# Generated by Django 3.1.5 on 2022-05-03 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0069_remove_nbateam_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='nbateam',
            name='city',
            field=models.ForeignKey(default=304, on_delete=django.db.models.deletion.CASCADE, to='exercises.city'),
            preserve_default=False,
        ),
    ]
