# Generated by Django 3.1.5 on 2022-05-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0072_nbateam_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nbateam',
            name='city',
        ),
    ]
